version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
